name: "fp"
services:
  app:
    container_name: app
    image: trafex/php-nginx
    ports:
      - "80:8080"
    volumes:
      - ./:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
  mysql:
    container_name: db
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: funpay
      MYSQL_ROOT_PASSWORD: funpay
      MYSQL_DATABASE: funpay
      MYSQL_USER: funpay
      MYSQL_PASSWORD: funpay